run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - gofmt
    - goimports

linters-settings:
  goimports:
    local-prefixes: github.com/andyrewlee/amux
  errcheck:
    check-type-assertions: true
